//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using EntityFramework.Common.Entities;

namespace Rockmelon.Repository.Entities
{
    public partial class Feedback : IBaseEntity
    {
        public string Description { get; set; }
        public Nullable<int> PageId { get; set; }
        public int Id { get; private set; }
        DateTimeOffset IBaseEntity.LastUpdatedOn { get; set; }
        public string LastUpdatedByUserId { get; set; }
        public bool IsActive { get; set; }
    }
}
