//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using EntityFramework.Common.Entities;

namespace Rockmelon.Repository.Entities
{
    public partial class Recipe : IBaseEntity
    {
        public string RecipeName { get; set; }
        
        public ICollection<Ingredient> Ingredients { get; set; }

        public int Id { get; private set; }
        public DateTimeOffset LastUpdatedOn { get; set; }
        public string LastUpdatedByUserId { get; set; }
        public bool IsActive { get; set; }
    }
}
